aliyun-oss:
  endpoint: yourEndpoint
  access-key-id: yourAccessKeyId
  access-key-secret: yourAccessKeySecret
  bucket-name: yourBucketName
  bucket-url: yourBucketUrl
  base-path: yourBasePath
captcha:
  key-long: 6
  img-width: 240
  img-height: 800
casbin:
  model-path: ./global/model.conf
email:
  to: xxx@qq.com
  from: xxx@163.com
  host: smtp.163.com
  secret: xxx
  nickname: test
  port: 465
  is-ssl: true
httpconfig:
  port: 8089
  mode: debug
  openredis: true
  opencaptcha: true
  osstype: local
  openratelimit: true
hua-wei-obs:
  path: you-path
  bucket: you-bucket
  endpoint: you-endpoint
  access-key: you-access-key
  secret-key: you-secret-key
jwt:
  key: "12334"
  expiretime: 86400
local:
  path: uploads/file
log:
  path: log
  maxsize: 10
  maxbackups: 10
  maxage: 10
  compress: true
mysql:
  host: 127.0.0.1
  port: "3306"
  username: root
  password: "123456"
  database: admin_cli
  logomode: true
qiniu:
  zone: ZoneHuaDong
  bucket: qiniu
  img-path: qiniu
  use-https: true
  access-key: qiniu
  secret-key: qiniu
  use-cdn-domains: true
ratelimit:
  qps: 3
redis:
  host: 127.0.0.1
  port: "6379"
  password: ""
  db: 0
salt: "11111"
tencent-cos:
  bucket: xxxxx-10005608
  region: ap-shanghai
  secret-id: xxxxxxxx
  secret-key: xxxxxxxx
  base-url: https:/gin.vue.admin
  path-prefix: github.com/flipped-aurora/gin-vue-admin/server
