httpConfig:
  port: 8089
  openRedis: true

mysql:
  host: 127.0.0.1
  port: "3306"
  userName: "root"
  password: "123456"
  database: "admin_cli"
  logoMode: true

redis:
  host: 127.0.0.1
  port: 6379
  password:
  db: 0

jwt:
  key: "12334"
  expireTime: 86400

log:
  path: log
  maxsize: 10
  maxBackups: 10
  maxAge: 10
  compress: true

openCache: false

hostName: "http://localhost:8080/"

salt: "123456789"