captcha:
  key-long: 6
  img-width: 240
  img-height: 800
casbin:
  model-path: ./global/model.conf
hostname: http://localhost:8080/
httpconfig:
  port: 8089
  mode: debug
  openredis: true
  oss-type: local
  opencaptcha: true
jwt:
  key: "12334"
  expiretime: 86400

log:
  path: log
  maxsize: 10
  maxbackups: 10
  maxage: 10
  compress: true

mysql:
  host: 127.0.0.1
  port: "3306"
  username: root
  password: "123456"
  database: admin_cli
  logomode: true

redis:
  host: 127.0.0.1
  port: "6379"
  password: ""
  db: 0

salt: "11111"

aliyun-oss:
  endpoint: yourEndpoint
  access-key-id: yourAccessKeyId
  access-key-secret: yourAccessKeySecret
  bucket-name: yourBucketName
  bucket-url: yourBucketUrl
  base-path: yourBasePath

hua-wei-obs:
  path: you-path
  bucket: you-bucket
  endpoint: you-endpoint
  access-key: you-access-key
  secret-key: you-secret-key

local:
  path: uploads/file

qiniu:
  zone: ZoneHuaDong
  bucket: ""
  img-path: ""
  use-https: false
  access-key: ""
  secret-key: ""
  use-cdn-domains: false

tencent-cos:
  bucket: xxxxx-10005608
  region: ap-shanghai
  secret-id: xxxxxxxx
  secret-key: xxxxxxxx
  base-url: https://gin.vue.admin
  path-prefix: github.com/flipped-aurora/gin-vue-admin/server

email:
  to: xxx@qq.com
  port: 465
  from: xxx@163.com
  host: smtp.163.com
  is-ssl: true
  secret: xxx
  nickname: test
