captcha:
  key-long: 6
  img-width: 240
  img-height: 800
casbin:
  model-path: ./global/model.conf
hostname: http://localhost:8080/
httpconfig:
  port: 8089
  mode: debug
  openredis: true
  opencaptcha: true
jwt:
  key: "12334"
  expiretime: 86400
log:
  path: log
  maxsize: 10
  maxbackups: 10
  maxage: 10
  compress: true
mysql:
  host: 127.0.0.1
  port: "3306"
  username: root
  password: "123456"
  database: admin_cli
  logomode: true
redis:
  host: 127.0.0.1
  port: "6379"
  password: ""
  db: 0
salt: "11111"
